### ISSUE TITLE
Errors in band math for algorithms Be16FLHblue & Zh10FLH 

### ISSUE THREAD

**Issue by RAJohansen** [RAJohansen/waterquality#12]
Both of these algorithms result in 0. Both of these need to be removed from S2 choices. 
Be16FLHblue c(2, 4, 2),  = 
(w529)   - (w644 + (w458 - w644))

Zh10FLH, c(4, 5, 4) = 
(w686)-(w715 + (w672-w715))

**Comment by RAJohansen** [comment]
@Nowosad,

Hey, I changed the above two algorithms to NA in https://github.com/RAJohansen/waterquality/blob/master/data-raw/wq_algorithms_prep.R but when I re built the package then re-installed in on my computer it still ran both of these algorithms. Am I missing a step?

**Comment by Nowosad** [comment]
Try it now - https://github.com/RAJohansen/waterquality/commit/072c276d1940ecf3012d676cbb4952a923de2894

**Comment by RAJohansen** [comment]
Excellent! 

What, if anything, did you do something?

**Comment by Nowosad** [comment]
I ran  the `wq_algorithms_prep.R` script.
