### ISSUE TITLE
Calculating line height algorithms

### ISSUE THREAD

**Issue by wbsalls** [RAJohansen/waterquality#16]
Hi,

Thanks for your contribution of this package. I want to check about two line height algorithms that you include: Go04MCI and Zh10FLH. I'm familiar with MCI and FLH, but not with the "Go04" and "Zh10" prefixes - are these meant to be different from the original algorithms? I ask because the calculation of both is different from how a line height algorithm is normally calculated.

The calculation for MCI in the waterquality package amounts to w709 - w753, and for FLH, w686 - w672. Below I attached an image showing how these two algorithms are normally calculated. Could you please clarify if I am missing something?

Thank you,
Wilson

![lineheight](https://user-images.githubusercontent.com/7197767/134971907-0be3763b-f862-48eb-b825-45a2f9f0c336.png)

**Comment by RAJohansen** [comment]
Attempted to resolve issue. Uses ratios of original algorithm wavelengths. This is not a elegant solution and might result in further issues.

Need to find a way to pull wavelength values for each sensor's band specifically.

**Comment by RAJohansen** [comment]
Major update to FLH and CI algorithms, including eliminating redundant algorithms.
