### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by RAJohansen** [RAJohansen/waterquality#17]
Update Docs to reflect algorithm changes.

**Comment by RAJohansen** [comment]
Jakub, I have updated all the code but having trouble getting the vignette to update using the new algorithms. It is still running vignette v 0.2.6 when everything should be v 0.3.0.

**Comment by Nowosad** [comment]
Is it still a problem? https://rajohansen.github.io/waterquality/articles/waterquality_vignette.html seems to be up-to-date...

**Comment by RAJohansen** [comment]
The "Type of Algorithm" and "All Algorithms" are pulling the out dated algorithms. This might be an issue with wq_calc. For example, Be16FLHviolet should now be Be16FLHviolet_S2. 

The wq_algorithms_prep function does not match the results from the wq_calc function.
